version: "3.8"

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: glms-sql-server-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password123!"
    ports:
      - "1433:1433"

  glms-api:
    build:
      context: ./GLMS-ST10104382.API
      dockerfile: Dockerfile
    container_name: glms-api
    ports:
      - "5001:8080"
    depends_on:
      - sql-server-db

  glms-frontend-web:
    build:
      context: ./GLMS-ST10104382
      dockerfile: Dockerfile
    container_name: glms-frontend-web
    ports:
      - "5002:8080"
    depends_on:
      - glms-api